### ISSUE TITLE
Umbrella issue: migration performance improvement

### ISSUE THREAD

**Issue by roycaihw** [kubernetes-sigs/kube-storage-version-migrator#78]
Talked with @caesarxuchao. There are a few potential performance improvement we can do to the migrator controller: 

- [ ] Don't [retry on UPDATE conflict](https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/78600c35396b3992e058163885a16d677bcb3ee8/pkg/migrator/errors.go#L66-L67). A [conflict](https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/78600c35396b3992e058163885a16d677bcb3ee8/pkg/migrator/core.go#L243-L247) means the object has been written by another client, and has the up-to-date storage version. 
- [ ] Don't [deserialize GET result](https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/78600c35396b3992e058163885a16d677bcb3ee8/pkg/migrator/core.go#L63-L69) before UPDATE. We already skip doing conversion to tolerate potential client-server skew. We can skip doing (de)serialization and just putting the data blob we got. 
- [x] ~Don't [GET](https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/78600c35396b3992e058163885a16d677bcb3ee8/pkg/migrator/core.go#L237-L242). Same as don't retry on UPDATE, we can skip GET and use the result from the LIST.~ We do [this](https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/78600c35396b3992e058163885a16d677bcb3ee8/pkg/migrator/core.go#L205) already. 

/priority important-long-term
/kind cleanup
